#!/usr/bin/env sh
# This file is sourced by video/videoencode/dvb-t/dvb-c to set some defaults.

# The first part is to set some defaults common for dvb-t and video{,encode}.
# Look at the function SetDefaults in the scripts to see what can be set here.

# titleopt=

# Now only dvb-t and dvb-c

# $dvb is a shortcut for $dvbt || $dvbc
if $dvb
then	# if $dvbt
	# then	channels=~/.tzap/channels.conf
	# elif $dvbc
	# then	channels=~/.czap/channels.conf
	# fi
	# pass=r
	# adapter=1
	# frontend=1
	# demux=1
	# force=:
	# verbose=false
	return
fi

# Now everything common to video and videoencode

#

# Now only video

if ! $fromfile
then	test -r /dev/videotv && device='/dev/videotv'
	#adevice=/dev/dsp3
	#immediatemode=0
	#alsa=:
	#inputnr=2
	#inputchannel='SE12'
	#brightness='-25'
	#br=1400
	#hqdn=''
	#loudness=55
	#loudnessplay=100
	#carddimension='width=768:height=576'
	#carddimension=
	#cropcmd=false
	return
fi

# Now only videoencode
